version 2
orbs:
  node: circleci/node@1.1.6
jobs:
    build:
        environment:
            IMAGE_NAME : 56faisal/typescript-starter
        docker: 
            - image circleci/buildpack-deps
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Docker image
                command: docker build -t 56faisal/typescript-starter:latest .

workflows:
    version: 2
    jobs:
        - build:
            filters:
               branches:
                    only: master